services:
  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ruby-getting-started_development
    volumes:
      - mysql_volume:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  db-rundeck:
    container_name: db-rundeck
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rundeck
      MYSQL_USER: rundeck
      MYSQL_PASSWORD: rundeck
      TZ: Asia/Tokyo
    volumes:
      - rundeck_mysql_volume:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: password
      REDIS_URL: redis://redis:6379/0
      # appがdatadogライブラリを初期化する時に使用
      DATADOG_HOST: datadog
      # トレース送信先としてdd-agentを指定。
      # dd-agentコンテナの両方で同じ値にする必要がある
      DD_AGENT_HOST: dd-agent
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - db
      - datadog
      - redis
  redis:
    container_name: redis
    build:
      context: ./docker/local/redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    volumes:
      - .data/redis:/data
      - ./docker/local/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=password
  rundeck:
    container_name: rundeck
    build:
      context: ./docker/local/rundeck
      dockerfile: Dockerfile
    platform: linux/amd64
    environment:
      RUNDECK_DATABASE_DRIVER: org.mariadb.jdbc.Driver
      RUNDECK_DATABASE_USERNAME: rundeck
      RUNDECK_DATABASE_PASSWORD: rundeck
      RUNDECK_DATABASE_URL: jdbc:mysql://db-rundeck/rundeck?autoReconnect=true&useSSL=false
      RUNDECK_GRAILS_URL: http://localhost:4440
    volumes:
      - ./rundeck/data:/home/rundeck/server/data
      - ./rundeck/job:/home/rundeck/var/logs/rundeck
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 4440:4440
    depends_on:
      - db-rundeck
  datadog:
    container_name: dd-agent
    build: datadog
    environment:
      DD_API_KEY: ${DD_API_KEY}
      # 他コンテナからのカスタムメトリクスをAgentが受信できるようにする
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: true
      # トレースを有効化
      DD_APM_ENABLED: true
      # 他コンテナからのトレースをAgentが受信できるようにする
      DD_APM_NON_LOCAL_TRAFFIC: true
      # appコンテナがAgentに転送できるようにする
      DD_AGENT_HOST: dd-agent
      DD_SITE: ap1.datadoghq.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro

volumes:
  mysql_volume: {}
  rundeck_mysql_volume: {}
