version: 2.1

# orbs:
#   heroku: circleci/heroku@2.0
jobs:
  purge-all:
    docker:
      - image: cimg/base:stable
    steps:
      - run:  
          name: Purge Fastly Cache
          command:             curl -X POST \
              -H "Fastly-Key: ${FASTLY_KEY}" \
              -H "Accept: application/json" \
              "https://api.fastly.com/service/${SERVICE_ID}/purge_all"
      
  # NOTE: 使わないのでコメントアウトした
  # deploy:
  #   executor: heroku/default
  #   steps:
  #     - checkout
  #     - heroku/install
  #     - heroku/deploy-via-git

workflows:
  heroku_deploy:
    jobs:
      - purge-all
      # - deploy    

# NOTE: Dockerイメージビルドは使ってないので、コメントアウト
# jobs:
#   build:
#     # Docker認証してイメージ取得
#     docker:
#       - image: captainkaeru/ruby-getting-started-app-prod:latest
#         auth:
#           username: $DOCKERHUB_LOGIN
#           password: $DOCKERHUB_PASSWORD
#     steps:
#       # TODO: あとからコメント解除する
#       # - checkout
#       ## Dockerイメージにタグ付けする
#       # - run:
#       #     name: Tag Docker Image for Heroku
#       #     command: docker tag captainkaeru/ruby-getting-started-app-prod:latest registry.heroku.com/ruby-getting-started-app-prod/web
#       - run:
#           name: Notify Build Complete
#           command: echo "Build completed"

# workflows:
#   deploy-prod:
#     jobs:
#       - build
