# Dockerコンテナ内ではrootのまま動かす（admグループが存在しないため）
$PrivDropToUser root
$PrivDropToGroup root

$DefaultNetstreamDriverCAFile /etc/ssl/certs/ca-certificates.crt
$ActionSendStreamDriver ossl
$ActionSendStreamDriverMode 1
$ActionSendStreamDriverAuthMode x509/name
$ActionSendStreamDriverPermittedPeer *.collector.na-01.cloud.solarwinds.com

$template SWOFormat,"<%pri%>1 %timestamp:::date-rfc3339% %HOSTNAME% %app-name% %procid% %msgid% [${PAPERTRAIL_TOKEN}@41058]%msg:::sp-if-no-1st-sp%%msg%"

*.* @@syslog.collector.na-01.cloud.solarwinds.com:6514;SWOFormat
