name: Purge All for CloudFront

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: '実行確認: "prod" と入力してください'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

env:
  AWS_ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/XXX

jobs:
  purge_all:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.confirm == 'prod' }}
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1
      - name: CloudFront Cache Invalidation
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
